
@baseUrl = http://localhost:8080



#### GET

GET  {{baseUrl}}/gift


#### POST 

POST {{baseUrl}}/gift
Content-Type: application/json

{
    "title": "heading 4",
    "img": "/img/arrival.jpg",
    "description": "dada tttnda mdadada dada adadadaa  adahghjjj gdthyjy fsfy",
    "price": 101
}




#### POST
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "fullName": "Usman ghani",
    "email": "usmanghani@gmail.com",
    "password": "dragan321"
}


#### POST
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "usmanghani@gmail.com",
    "password": "dragan32da1"
}










