
@baseUrl = http://localhost:8080



#### GET

GET  {{baseUrl}}/gift


#### POST 

POST {{baseUrl}}/gift
Content-Type: application/json

{
    "title": "heading 656",
    "img": "/img/arrival.jpg",
    "description": "dada tttnda mdadada dada adadadaa  adahghjjj gdthyjy fsfy",
    "price": 200
}






